name: Tests

on:
  pull_request:
    paths-ignore:
      - "docs/**"
      - "examples/**"
  push:
    branches:
      - main
    paths-ignore:
      - "docs/**"
      - "examples/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    name: Run tests on ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11", "3.12", "3.13"]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          poetry-version: latest
          install-extra-deps: true  # This installs Poetry and its dependencies

      # Cache Poetry dependencies to speed up the build
      - name: Cache Poetry dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pypoetry
            .venv
          key: ${{ runner.os }}-poetry-${{ hashFiles('poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-

      - name: Install dependencies
        run: poetry install --no-interaction --no-ansi --with dev

      - name: Run pre-commit
        run: poetry run pre-commit run --all-files

      - name: Run tests
        run: poetry run pytest
